### ISSUE TITLE
Error al cargar el servidor

### ISSUE THREAD

**Issue by MaxJoker149** [Gonzaa3007/UhcMeetup#2]
[04:23:18 WARN]: java.io.FileNotFoundException: https://api.spigotmc.org/simple/0.2/index.php?action=getResource&id=111306
[04:23:18 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1993)
[04:23:18 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
[04:23:18 WARN]:        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
[04:23:18 WARN]:        at UhcMeetup-1.2-all.jar//com.github.gonzq.uhcmeetup.UpdateChecker.lambda$checkNow$5(UpdateChecker.java:336)
[04:23:18 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101)
[04:23:18 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[04:23:18 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[04:23:18 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[04:23:18 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[04:23:18 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[04:23:18 WARN]: [UhcMeetup] Could not check for updates.

**Comment by Gonzaa3007** [comment]
Gracias por reportar. Fixeado
